projectname = "千金药业"
# 可配置网络代理，支持 http/https 协议
# proxyURL := "http://proxyuser:proxypassword@proxy_ip:proxy_port"
proxyurl = "http://wshoto:123qazwsx@172.18.0.17:9253"

[nacos]
server = "http://192.9.253.198:8848"
username = "nacos"
password = "nacos"
namespace = "qw-uat"

[tenant]
[[tenant.corp]]
corpid = "wxbe45d6b56a61e293"
convenabled = true
[[tenant.corp]]
corpid = "ww70adef74dc10951c"
convenabled = true
[[tenant.corp]]
corpid = "wwd4fc7dcb8f5a0d99"
convenabled = true
[[tenant.corp]]
corpid = "ww6b882761610096ad"
convenabled = true
[[tenant.corp]]
corpid = "wwe2007d5a571677f3"
convenabled = false

[inspection]
# 配置定时任务，每日巡检的发送时间：09:30 - 10:00
scheducron = "*/3 * * * *"
# 测试-每日巡检机器人
robotkey = "8ab989f5-d86f-4c99-b95f-5d23a30eb351"
# 告警@人 ["lanpang", "mark"]
userlist = []

[crontab]
inspectjob = true
testjob = true

[pg]
ip = "192.9.253.195"
port = 5432
username = "postgres"
password = "wshoto@2022"
sslmode = false

[es]
ip = "192.9.253.197"
port = 9200
username = "elastic"
password = "wshoto@2022"
sslmode = false