projectname = "测试企业"
# 可配置网络代理，支持 http/https 协议
# proxyURL := "http://proxyuser:proxypassword@proxy_ip:proxy_port"
proxyurl = ""
# vm数据库地址，示例：http://xxxx:8428
victoriaMetrics = ""
# 会话存档文件路径，示例：/data/nfs_data/attachment/ca-attachment
# 数据保存到对象存储就不用填写
nasDir = ""
# 出网域名检测列表
domainListName = "domain_list.txt"

# 租户配置，如果是服务商模式，租户填写加密 ID
[tenant]
    [[tenant.corp]]
        corpid = "xxxxxxxx"
        convenabled = true # 是否开通会话存档功能
    [[tenant.corp]]
        corpid = "xxxxxxxx"
        convenabled = true

# 定时任务
[cron]
    [cron.tenant]
        crontab = true # 是否启动
        scheducron = "30 09 * * *"
    [cron.doris]
        crontab = true
        scheducron = "30 09 * * *"
    [cron.message]
        crontab = true
        scheducron = "0 10 * * *"

# 告警通知
[notify]
    # 默认机器人，支持配置多个，["xxx", "xxx"]
    # 租户巡检机器人："5c8daf9d-bebb-4453-bab4-aa3fe56eeac3"
    # 大数据机器人："58d6b94c-27bc-46d2-bb64-788c7329b1a1"
    # 会话数机器人："4fbb66be-21c7-42f2-aa27-e90256d540da"
    robotkey = ["ed234722-6889-4047-a56c-02dd58d0d11b"] # 默认为部署组机器人，也可配置个人机器人
    # 默认告警@人 示例：["lanpang", "mark"]
    userlist = []
    [notify.notifier.tenant]
        robotkey = ["5c8daf9d-bebb-4453-bab4-aa3fe56eeac3"]
    [notify.notifier.doris]
        robotkey = ["58d6b94c-27bc-46d2-bb64-788c7329b1a1"]
    [notify.notifier.message]
        robotkey = ["4fbb66be-21c7-42f2-aa27-e90256d540da"]

[pg]
    ip = "x.x.x.x"
    port = 5432
    username = "postgres"
    password = "xxx"
    sslmode = false

[es]
    ip = "x.x.x.x"
    port = 9200
    username = "elastic"
    password = "xxx"
    sslmode = false

[doris]
    ip = "x.x.x.x"
    port = 9030
    username = "root"
    password = "xxx"
    sslmode = false
    httpPort = 18030

[redis]
    addr = "x.x.x.x:6379"
    Password = "xxxx"
    DB = 0

[nacos]
    server = "http://x.x.x.x:8848"
    username = "nacos"
    password = "nacos"
    namespace = "qw-uat"

[rocketmq]
    rocketmqDashboard = "http://x.x.x.x:8081"

[metric]
    enable = false
    port = "8090"
    healthApi = "/actuator/test"

# PG 拆库的配置，老百姓项目专用
[customer]
    ip = ""
    port = 5432
    username = ""
    password = ""
    sslmode = false