projectname = "测试企业"
# 可配置网络代理，支持 http/https 协议
# proxyURL := "http://proxyuser:proxypassword@proxy_ip:proxy_port"
proxyurl = ""

[tenant]
# 启用定时任务
crontab = true
# 配置定时任务，每天09:30启动巡检任务
scheducron = "30 09 * * *"
# 巡检机器人，支持配置多个机器人
robotkey = ["xxxxxx-d86f-4c99-b95f-5d23a30eb351"]
# 告警@人 ["lanpang", "mark"]
userlist = []

[[tenant.corp]]
corpid = "xxxxxxxx"
# 是否开通会话存档功能
convenabled = true

[pg]
ip = "x.x.x.x"
port = 5432
username = "postgres"
password = "xxx"
sslmode = false

[es]
ip = "x.x.x.x"
port = 9200
username = "elastic"
password = "xxx"
sslmode = false

[doris]
# 启用定时任务
crontab = true
# 配置定时任务，每天09:30启动巡检任务
scheducron = "30 09 * * *"
# 巡检机器人，支持配置多个机器人
robotkey = ["xxxxxx-d86f-4c99-b95f-5d23a30eb351"]

[doris.config]
ip = "x.x.x.x"
port = 9030
username = "root"
password = "xxx"
sslmode = false

[nacos]
server = "http://x.x.x.x:8848"
username = "nacos"
password = "nacos"
namespace = "qw-uat"

[rocketmq]
rocketmqDashboard = "http://x.x.x.x:8081"
nameServer = "x.x.x.x:9876"

[metric]
# 定义 metric 的端口
port = "8090"
# 启动微服务接口监控
wsapp = true
# rocketmq 监控
rocketmq = true
# 当前会话数
conversation = true