version: "3.8"
services:
  vhagar:
    image: ka-tcr.tencentcloudcr.com/middleware/vhagar:v1.0
    container_name: vhagar
    volumes:
      - ./config.toml:/app/config.toml
    restart: unless-stopped
